config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, lambda{|u| u.admin?} do
    mount Sidekiq::Web => "/sidekiq"
  end

  use_doorkeeper
 
  namespace :api do
    namespace :v1 do
      resource :profiles, only: [] do
        get :me, on: :collection
        get :others, on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, except: [:new, :edit], shallow: true
      end
    end
  end
  
  
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  
  as :user do
    namespace :user do
      resources :bounties, only: [:index, :show]
    end
  end

  scope :auth do
    resource :users, except: :all do
      post :enter_email
    end
  end

  concern :votable do
    member do
      patch :vote_yes
      patch :vote_no
      patch :cancel_vote
    end
  end
  
  resources :questions, except: [:new, :edit], concerns: [:votable] do
    resources :answers, except: [:new, :edit], shallow: true, concerns: [:votable] do
      resources :comments, only: [:create], defaults: { commentable_type: 'answer' }

      member do
        patch :mark_as_the_best
      end
    end

    resources :comments, only: [:create], defaults: { commentable_type: 'question' }
    
    member do
      post :subscribe, to: 'subscriptions#create', as: 'subscribe'
      delete :unsubscribe, to: 'subscriptions#destroy', as: 'unsubscribe'
    end
  end

  resources :files, only: [:destroy]
  resources :links, only: [:destroy]
  
  get 'search', to: 'search#index', as: 'search'

  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_header.html.slim
.top-bar
  .top-bar-left
    ul.menu
      li.menu-text
        = link_to 'QNA Project', root_path, class: "project"
  .top-bar-right
    ul.menu 
      - if user_signed_in?
          li= link_to "My bounties", user_bounties_path 
          li= link_to "Sign out", destroy_user_session_path, method: :delete
      - else
        - if controller_name != 'sessions' && controller_name != 'passwords' && controller_name != 'registrations'
            li= link_to "Sign in", new_user_session_path

app/views/shared/_search.html.slim
.grid-container
  .search-bar
    = render 'search/search_form'
    

app/views/shared/_subscriptions.html.slim
ul class="menu vertical align-center subscription-actions-#{ subscriptionable.id }"
  - if current_user 
    - if current_user.subscribed_to?(subscriptionable)
        li = button_to polymorphic_path(subscriptionable, action: :unsubscribe), 
                class: "button button-set", 
                method: :patch, 
                remote: true, 
                data: { subscriptionable_id: subscriptionable.id },
                style: "margin:0;padding:0;"
          svg aria-hidden="true" class="svg-icon m0 iconMail" width="20" height="20" viewBox="0 0 24 24"
            path d="M 4 4 C 2.895 4 2 4.895 2 6 L 2 18 C 2 19.105 2.895 20 4 20 L 20 20 C 21.105 20 22 19.105 22 18 L 22 6 C 22 4.895 21.105 4 20 4 L 4 4 z M 4 6 L 20 6 L 20 7.0019531 L 12 12 L 4 7.0019531 L 4 6 z M 4 9.0019531 L 12 14 L 20 9.0019531 L 20 18 L 4 18 L 4 9.0019531 z"
    - else
        li = button_to polymorphic_path(subscriptionable, action: :subscribe), 
                  class: "button button-unset", 
                  method: :patch, 
                  remote: true, 
                  data: { subscriptionable_id: subscriptionable.id },
                  style: "margin:0;padding:0;"
          svg aria-hidden="true" class="svg-icon m0 iconMail" width="20" height="20" viewBox="0 0 24 24"
            path d="M 4 4 C 2.895 4 2 4.895 2 6 L 2 18 C 2 19.105 2.895 20 4 20 L 20 20 C 21.105 20 22 19.105 22 18 L 22 6 C 22 4.895 21.105 4 20 4 L 4 4 z M 4 6 L 20 6 L 20 7.0019531 L 12 12 L 4 7.0019531 L 4 6 z M 4 9.0019531 L 12 14 L 20 9.0019531 L 20 18 L 4 18 L 4 9.0019531 z"

app/views/shared/_votes.html.slim
ul class="menu vertical align-center vote-actions-#{ votable.id }"
  - if current_user == nil || current_user&.author_of?(votable)
      li
        div class="button button-unset button-disabled" style="margin:0;padding:0;" 
          svg aria-hidden="true" class="svg-icon m0 iconArrowUpLg" width="20" height="20" viewBox="0 0 36 36"
            path d="M2 26h32L18 10 2 26z"
      li
        .vote-rating data-votable-id=votable.id = votable.rating
      li
        div class="button button-unset button-disabled" style="margin:0;padding:0;"
          svg aria-hidden="true" class="svg-icon m0 iconArrowDownLg" width="20" height="20" viewBox="0 0 36 36"
            path d="M2 10h32L18 26 2 10z"
  - else
    - if current_user&.voted_for?(votable)
        - if current_user.voted_for_up?(votable)
            li = button_to polymorphic_path(votable, action: :cancel_vote), 
                    class: "button button-set", 
                    method: :patch, 
                    remote: true, 
                    data: { votable_id: votable.id },
                    style: "margin:0;padding:0;"
              svg aria-hidden="true" class="svg-icon m0 iconArrowUpLg" width="20" height="20" viewBox="0 0 36 36"
                path d="M2 26h32L18 10 2 26z"
            li
              .vote-rating data-votable-id=votable.id = votable.rating
            li
              div class="button button-unset button-disabled" style="margin:0;padding:0;"
                svg aria-hidden="true" class="svg-icon m0 iconArrowDownLg" width="20" height="20" viewBox="0 0 36 36"
                  path d="M2 10h32L18 26 2 10z"
        - else
            li
              div class="button button-unset button-disabled" style="margin:0;padding:0;" 
                svg aria-hidden="true" class="svg-icon m0 iconArrowUpLg" width="20" height="20" viewBox="0 0 36 36"
                  path d="M2 26h32L18 10 2 26z"
            li
              .vote-rating data-votable-id=votable.id = votable.rating
            li = button_to polymorphic_path(votable, action: :cancel_vote), 
                    class: "button button-set", 
                    method: :patch, 
                    remote: true, 
                    data: { votable_id: votable.id },
                    style: "margin:0;padding:0;"
              svg aria-hidden="true" class="svg-icon m0 iconArrowDownLg" width="20" height="20" viewBox="0 0 36 36"
                path d="M2 10h32L18 26 2 10z"

    - else
        li = button_to polymorphic_path(votable, action: :vote_yes), 
                  class: "button button-unset", 
                  method: :patch, 
                  remote: true, 
                  data: { votable_id: votable.id },
                  style: "margin:0;padding:0;"
          svg aria-hidden="true" class="svg-icon m0 iconArrowUpLg" width="20" height="20" viewBox="0 0 36 36"
            path d="M2 26h32L18 10 2 26z"
        li
          .vote-rating data-votable-id=votable.id = votable.rating
        li = button_to polymorphic_path(votable, action: :vote_no), 
                class: "button button-unset", 
                method: :patch, 
                remote: true, 
                data: { votable_id: votable.id },
                style: "margin:0;padding:0;"
          svg aria-hidden="true" class="svg-icon m0 iconArrowDownLg" width="20" height="20" viewBox="0 0 36 36"
            path d="M2 10h32L18 26 2 10z"
          