config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, lambda{|u| u.admin?} do
    mount Sidekiq::Web => "/sidekiq"
  end

  use_doorkeeper
 
  namespace :api do
    namespace :v1 do
      resource :profiles, only: [] do
        get :me, on: :collection
        get :others, on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, except: [:new, :edit], shallow: true
      end
    end
  end
  
  
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  
  as :user do
    namespace :user do
      resources :bounties, only: [:index, :show]
    end
  end

  scope :auth do
    resource :users, except: :all do
      post :enter_email
    end
  end

  concern :votable do
    member do
      patch :vote_yes
      patch :vote_no
      patch :cancel_vote
    end
  end
  
  resources :questions, except: [:new, :edit], concerns: [:votable] do
    resources :answers, except: [:new, :edit], shallow: true, concerns: [:votable] do
      resources :comments, only: [:create], defaults: { commentable_type: 'answer' }

      member do
        patch :mark_as_the_best
      end
    end

    resources :comments, only: [:create], defaults: { commentable_type: 'question' }
    
    member do
      post :subscribe, to: 'subscriptions#create', as: 'subscribe'
      delete :unsubscribe, to: 'subscriptions#destroy', as: 'unsubscribe'
    end
  end

  resources :files, only: [:destroy]
  resources :links, only: [:destroy]
  
  get 'search', to: 'search#index', as: 'search'

  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Linkable
  include Votable
  include Commentable
  
  belongs_to :question, touch: true
  belongs_to :user

  has_many_attached :files

  default_scope { order(best_answer: :desc).order(:created_at) }

  validates :body, presence: true
  validates :question_id, uniqueness: { scope: :best_answer }, if: :best_answer?

  after_create :notify_subscribed_users

  def mark_as_the_best_answer!
    transaction do
      self.question.answers.update_all(best_answer: false)
      self.question.bounty&.update(user: self.user)
      self.reload
      self.update!(best_answer: true)
    end
  end

  private
    
    def notify_subscribed_users
      NotifySubscribedUsersJob.perform_later(self)
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :find_question, only: %w[create]
  before_action :set_answer, only: %w[update destroy mark_as_the_best]
  before_action :gon_user
  after_action :publish_answer, only: %w[create]

  authorize_resource

  def create
    @answer = current_user.answers.new(answer_params)
    @answer.question = @question
    @answer.save

    if @answer.save
      render json: @answer
    else
      render json: { errors: @answer.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def update
    @answer.update(answer_params) if current_user.author_of?(@answer)
    @question = @answer.question
    @comment = Comment.new

    respond_to do |format|
      format.js
    end
  end

  def destroy
    @answer.destroy if current_user.author_of?(@answer)
    @question = @answer.question
    
    respond_to do |format|
      format.js
    end
  end

  def mark_as_the_best
    @question = @answer.question
    @answer.mark_as_the_best_answer! if current_user.author_of?(@question)
    @comment = Comment.new
    
    respond_to do |format|
      format.js 
    end
  end

  private

    def find_question
      @question = Question.with_attached_files.find(params[:question_id])
    end

    def set_answer
      @answer = Answer.with_attached_files.find(params[:id])
      gon.answer_id = @answer.id
    end

    def answer_params
      params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url])
    end
    
    def publish_answer
      return if @answer.errors.any?

      ActionCable.server.broadcast(  
        "answers_channel_#{ @answer.question_id }", 
        { 
          answer: @answer, 
          question: @answer.question,
          attachments: formatted_attachments(@answer),
          links: formatted_links(@answer),
          comment: @answer.comments.new
        }
      ) 
    end

    def gon_user
      gon.user_id = current_user&.id 
    end

    def formatted_attachments(answer)
       answer.files.attachments.inject([]) { |arr, a| 
         arr << { 
           id: a.id, 
           url: rails_blob_url(a), 
           filename: a.blob.filename, 
           user_id: a.record.user_id 
         } 
       }
    end

    def formatted_links(answer)
      @answer.links.inject([]) { |arr, l| 
        arr << { 
          id: l.id, 
          name: l.name, 
          url: l.url, 
          linkable_type: l.linkable_type, 
          linkable_id: l.linkable_id, 
          user_id: answer.user_id
        } 
      }
    end
end

app/controllers/api/v1/answers_controller.rb
class API::V1::AnswersController < API::V1::BaseController
  before_action :set_question, only: %w[index create]
  before_action :set_answer, only: %w[show update destroy]
  
  authorize_resource

  def index
    @answers = Answer.where(question: @question)
    json_response(@answers, :ok, each_serializer: AnswerListSerializer)
  end

  def show
    json_response(@answer)
  end

  def create
    @answer = current_resource_owner.answers.new(answer_params)
    @answer.question = @question
    @answer.save!

    json_response(@answer, :created) 
  end

  def update
    @answer.update(answer_params)
    head :no_content
  end

  def destroy
    @answer.destroy
    head :no_content
  end

  private
    def set_question
      @question = Question.find(params[:question_id])
    end

    def set_answer
      @answer = Answer.with_attached_files.find(params[:id])
    end
    
    def answer_params
      params.require(:answer).permit(:body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_actions.html.slim
= render 'shared/votes', votable: answer, current_user: current_user
ul class="menu vertical align-center best-answer-action-#{ answer.id }"
  - if current_user&.author_of?(answer.question)
      - if answer.best_answer?
          li 
            div class="button button-set button-disabled" style="margin:0;padding:0;"
              svg aria-hidden="true" class="svg-icon iconStar" width="20" height="20" viewBox="0 0 18 18"
                path d="M9 12.65l-5.29 3.63 1.82-6.15L.44 6.22l6.42-.17L9 0l2.14 6.05 6.42.17-5.1 3.9 1.83 6.16L9 12.65z"
      - else
          li = button_to mark_as_the_best_answer_path(answer), method: :patch, remote: true, class: "button button-unset", style: "margin:0;padding:0;"
            svg aria-hidden="true" class="svg-icon iconStar" width="20" height="20" viewBox="0 0 18 18"
              path d="M9 12.65l-5.29 3.63 1.82-6.15L.44 6.22l6.42-.17L9 0l2.14 6.05 6.42.17-5.1 3.9 1.83 6.16L9 12.65z"
  - else
      - if answer.best_answer?
          li 
            div class="button button-set button-disabled" style="margin:0;padding:0;"
              svg aria-hidden="true" class="svg-icon iconStar" width="20" height="20" viewBox="0 0 18 18"
                path d="M9 12.65l-5.29 3.63 1.82-6.15L.44 6.22l6.42-.17L9 0l2.14 6.05 6.42.17-5.1 3.9 1.83 6.16L9 12.65z"
      - else
          li
            div class="button button-unset button-disabled" style="margin:0;padding:0;"
              svg aria-hidden="true" class="svg-icon iconStar" width="20" height="20" viewBox="0 0 18 18"
                path d="M9 12.65l-5.29 3.63 1.82-6.15L.44 6.22l6.42-.17L9 0l2.14 6.05 6.42.17-5.1 3.9 1.83 6.16L9 12.65z"
  - if current_user&.author_of?(answer)
      li = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
      li = link_to 'Delete', answer_path(answer), method: :delete, remote: true, data: { confirm: 'Are you sure?' }

app/views/answers/_answer.html.slim
div class="grid-x row-answer-#{ answer.id }-errors"
- cache [answer, current_user] do
  div class="grid-x row-answer-#{ answer.id } #{ answer.best_answer? ? 'best-answer' : '' }"
    .cell.answer-cell
      .grid-x.grid-padding-x.grid-margin-x
        .cell.small-1.shrink style="border-right: 1px solid #e6e6e6;padding-left:0;"
          = render 'answers/actions', answer: answer, current_user: current_user
        .cell.auto style="padding:0;margin:0"
          .grid-y
            .cell style="padding-left:0;"
              = render 'answers/tab_menu', answer: answer, current_user: current_user
          .grid-y
            .cell
              .grid-x
                .cell
                  p
                    = answer.body
                  = render 'answers/edit_form', answer: answer
            .cell
              .grid-x.grid-margin-x
                .cell
                  = render 'answers/tabs', answer: answer, current_user: current_user
      hr 

app/views/answers/_edit_form.html.slim
.grid-y
  .cell.hidden id="edit-answer-#{ answer.id }"
    = form_for answer, remote: true do |f|
      .grid-x
        .cell 
          = f.label :body
          = f.text_area :body
      .grid-x
        .cell
          = f.label :files
          = f.file_field :files, multiple: true, direct_upload: true
      .grid-x
        .cell 
          .links
            = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'
      .grid-x
        .cell
          = f.submit 'Save your answer', class: 'button primary'

app/views/answers/_new_form.html.slim
- if user_signed_in?
    .grid-x.align-left
      .cell.small-12.callout
        .grid-y
          .cell id="new-answer"
            = form_for [@question, @answer], remote: true do |f|
              .grid-x
                .cell 
                  = f.label :body
                  = f.text_area :body
                .cell 
                  = f.label :files
                  = f.file_field :files, multiple: true, direct_upload: true
                .cell
                  .links
                    = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'
                .cell 
                  = f.submit 'Post your answer', class: 'button primary'

app/views/answers/_tab_menu.html.slim
ul.menu.align-right.tabs(id="answer-#{ answer.id }-tabs" data-tabs) 
  li.tabs-title.is-active
    = link_to 'Files', "#answer-#{ answer.id }-panel1", 'id': "answer-#{ answer.id }-panel1-label", 'data-tabs-target': "answer-#{ answer.id }-panel1"
  li.tabs-title 
    = link_to 'Links', "#answer-#{ answer.id }-panel2", 'id': "answer-#{ answer.id }-panel2-label", 'data-tabs-target': "answer-#{ answer.id }-panel2"
  li.tabs-title 
    = link_to 'Comments', "#answer-#{ answer.id }-panel3", 'id': "answer-#{ answer.id }-panel3-label", 'data-tabs-target': "answer-#{ answer.id }-panel3"

app/views/answers/_tabs.html.slim
.tabs-content data-tabs-content="answer-#{ answer.id }-tabs"
  = render 'answers/tabs/files_panel', answer: answer
  = render 'answers/tabs/links_panel', answer: answer
  = render 'answers/tabs/comments_panel', answer: answer

app/views/answers/destroy.js.erb
$('.row-answer-<%= @answer.id %>').remove();

app/views/answers/destroy_file_attachment.js.erb
$('.row-file-<%= @attachment.id %>').remove();

app/views/answers/mark_as_the_best.js.erb
<% if @answer.errors.blank? %>
  $("div[class*=row-answer-]").remove();
  $('<%= j render @question.answers.with_attached_files %>').insertBefore($('.answer-errors')); 
<% else %>
  $('.row-answer-<%= @answer.id %>-errors').html("<%= render 'shared/errors', resource: @answer %>");
<% end %>
$(document).foundation();

app/views/answers/update.js.erb
<% if @answer.errors.blank? %>
  $('.row-answer-<%= @answer.id %>-errors').replaceWith("")
  $('.row-answer-<%= @answer.id %>').replaceWith('<%= j render @answer %>');
<% else %>
    $('.row-answer-<%= @answer.id %>-errors').html("<%= render 'shared/errors', resource: @answer %>");
<% end %>