config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, lambda{|u| u.admin?} do
    mount Sidekiq::Web => "/sidekiq"
  end

  use_doorkeeper
 
  namespace :api do
    namespace :v1 do
      resource :profiles, only: [] do
        get :me, on: :collection
        get :others, on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, except: [:new, :edit], shallow: true
      end
    end
  end
  
  
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  
  as :user do
    namespace :user do
      resources :bounties, only: [:index, :show]
    end
  end

  scope :auth do
    resource :users, except: :all do
      post :enter_email
    end
  end

  concern :votable do
    member do
      patch :vote_yes
      patch :vote_no
      patch :cancel_vote
    end
  end
  
  resources :questions, except: [:new, :edit], concerns: [:votable] do
    resources :answers, except: [:new, :edit], shallow: true, concerns: [:votable] do
      resources :comments, only: [:create], defaults: { commentable_type: 'answer' }

      member do
        patch :mark_as_the_best
      end
    end

    resources :comments, only: [:create], defaults: { commentable_type: 'question' }
    
    member do
      post :subscribe, to: 'subscriptions#create', as: 'subscribe'
      delete :unsubscribe, to: 'subscriptions#destroy', as: 'unsubscribe'
    end
  end

  resources :files, only: [:destroy]
  resources :links, only: [:destroy]
  
  get 'search', to: 'search#index', as: 'search'

  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question
  before_action :gon_user

  authorize_resource

  def create 
    current_user.subscribe!(@question) unless current_user.subscribed_to?(@question)
    
    render json: { question: @question, subscribed: current_user.subscribed_to?(@question) }
  end

  def destroy
    current_user.unsubscribe!(@question) if current_user.subscribed_to?(@question)

    render json: { question: @question, subscribed: current_user.subscribed_to?(@question) }
  end

  private
  
  def set_question
    @question = Question.find(params[:id])
  end

  def gon_user
    gon.user_id = current_user&.id
  end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_subscription.html.slim
ul class="menu vertical align-center subscription-actions-#{ question.id }"
  - if current_user 
    - if current_user.subscribed_to?(question)
        li = button_to unsubscribe_question_path(question), 
                class: "button button-set", 
                method: :delete, 
                remote: true, 
                data: { question_id: question.id },
                style: "margin:0;padding:0;"
          svg aria-hidden="true" class="svg-icon m0 iconMail" width="20" height="20" viewBox="0 0 24 24"
            path d="M 4 4 C 2.895 4 2 4.895 2 6 L 2 18 C 2 19.105 2.895 20 4 20 L 20 20 C 21.105 20 22 19.105 22 18 L 22 6 C 22 4.895 21.105 4 20 4 L 4 4 z M 4 6 L 20 6 L 20 7.0019531 L 12 12 L 4 7.0019531 L 4 6 z M 4 9.0019531 L 12 14 L 20 9.0019531 L 20 18 L 4 18 L 4 9.0019531 z"
    - else
        li = button_to subscribe_question_path(question), 
                  class: "button button-unset", 
                  method: :create, 
                  remote: true, 
                  data: { question_id: question.id },
                  style: "margin:0;padding:0;"
          svg aria-hidden="true" class="svg-icon m0 iconMail" width="20" height="20" viewBox="0 0 24 24"
            path d="M 4 4 C 2.895 4 2 4.895 2 6 L 2 18 C 2 19.105 2.895 20 4 20 L 20 20 C 21.105 20 22 19.105 22 18 L 22 6 C 22 4.895 21.105 4 20 4 L 4 4 z M 4 6 L 20 6 L 20 7.0019531 L 12 12 L 4 7.0019531 L 4 6 z M 4 9.0019531 L 12 14 L 20 9.0019531 L 20 18 L 4 18 L 4 9.0019531 z"