config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, lambda{|u| u.admin?} do
    mount Sidekiq::Web => "/sidekiq"
  end

  use_doorkeeper
 
  namespace :api do
    namespace :v1 do
      resource :profiles, only: [] do
        get :me, on: :collection
        get :others, on: :collection
      end

      resources :questions, except: [:new, :edit] do
        resources :answers, except: [:new, :edit], shallow: true
      end
    end
  end
  
  
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  
  as :user do
    namespace :user do
      resources :bounties, only: [:index, :show]
    end
  end

  scope :auth do
    resource :users, except: :all do
      post :enter_email
    end
  end

  concern :votable do
    member do
      patch :vote_yes
      patch :vote_no
      patch :cancel_vote
    end
  end
  
  resources :questions, except: [:new, :edit], concerns: [:votable] do
    resources :answers, except: [:new, :edit], shallow: true, concerns: [:votable] do
      resources :comments, only: [:create], defaults: { commentable_type: 'answer' }

      member do
        patch :mark_as_the_best
      end
    end

    resources :comments, only: [:create], defaults: { commentable_type: 'question' }
    
    member do
      post :subscribe, to: 'subscriptions#create', as: 'subscribe'
      delete :unsubscribe, to: 'subscriptions#destroy', as: 'unsubscribe'
    end
  end

  resources :files, only: [:destroy]
  resources :links, only: [:destroy]
  
  get 'search', to: 'search#index', as: 'search'

  root to: "questions#index"

  mount ActionCable.server => '/cable'
end

app/models/enter_email.rb
class EnterEmail
  include ActiveModel::Model

  attr_accessor :email

  validates :email, presence: true,:format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/ }
end

app/views/enter_emails/_enter_email.html.slim
.grid-container
  .grid-x.grid-padding-x.align-center
    .large-4.medium-6.small-12.cell.callout.form-section
      .grid-x.grid-padding-x
        .large-12.medium-12.small-12.text-center.header
          h1 Enter email
        .large-12.columns.cell
          = form_for(@enter_email, url: enter_email_users_path) do |f| 
            = render "shared/errors", resource: @enter_email
            .grid-x.grid-padding-x
              .large-12.medium-12.cell 
                = f.email_field :email, autofocus: true, autcomplete: "email", placeholder: "Enter email"
                = f.submit "Enter email", class: "button primary login-btn"